# Your site's URL root folder. 
#
# For example, if your site is going to be served 
# from whithin a folder such as "mysite", then you
# should type the base url as:
# 
# http://sitedomain/mysite or https://sitedomain/mysite if you have a certificate
#
# This is important because Hugo will generate all the links
# in your site relative to the baseURL typed here.

baseURL = "http://localhost/public"

# The default is English 
languageCode = "en-us"

# Your site's title
title = "Self"

# For displaying the copyright on the footer
copyright = "&copy; Your copyright"

# Set a number where pagination starts
paginate = 3

[params]

	# Enable copyright year (add `true` to enable)
	# The year changes automatically
	year = "true"

	# If you don't want the curriculum section just add `false`
	cv ="true"

    # Add your name
    author = "Your name"

    # For the profile image add an image in 'static/img' folder
    profileImage = "profile.png"

    # Add your site's title
    siteName = "Self Theme (title)"

    # Add your site's description
    description = "Build a website for yourself! (description)"

    # Add the links of the social sites you want on your menu section
    # If you don't want a specific account just add "disable" 
    # To disable all social buttons just add "true" to the `AllDisabled` variable

    AllDisabled = "false"
    linkedin = "#"
    github = "#"
    facebook = "#"
    instagram = "#"
    twitter = "#"
    snapchat = "#"
    mail = "#"
