# This theme was designed from scratch for anyone to use it with Hugo, mostly
# as a personal website, portfolio, blog or resume. While it has a mininal
# materialistic design, it supports features that are expected to be found in
# feature-rich themes and it's also responsive!

name = "Self"
license = "MIT"
licenselink = "https://github.com/NtinosNG/self/blob/master/LICENSE"
description = "A simple two-column theme for building a website for yourself."
homepage = "https://selftheme.netlify.com/"                                       # Visit to see a demo
tags = ["personal","portfolio","blog","resume","curriculum"]
features = ["responsive","minimal","material"]
min_version = "0.41"

[author]
  name = "Konstantinos Bazoukis"
  homepage = "https://kbazoukis.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
